// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
)

type Product struct {
	ID          int64
	UsersID     int64
	Metadata    json.RawMessage
	Description string
	Price       float64
	Tags        []string
	Location    string
	CreatedAt   sql.NullTime
}

type User struct {
	ID        int64
	Email     string
	Name      string
	Age       sql.NullInt16
	Biography sql.NullString
	Address   string
	Number    string
	CreatedAt sql.NullTime
}
