// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (users_id, metadata, description, price, tags, location)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, users_id, metadata, description, price, tags, location, created_at
`

type CreateProductParams struct {
	UsersID     int64
	Metadata    json.RawMessage
	Description string
	Price       string
	Tags        []string
	Location    string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.UsersID,
		arg.Metadata,
		arg.Description,
		arg.Price,
		pq.Array(arg.Tags),
		arg.Location,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UsersID,
		&i.Metadata,
		&i.Description,
		&i.Price,
		pq.Array(&i.Tags),
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, users_id, metadata, description, price, tags, location, created_at FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UsersID,
		&i.Metadata,
		&i.Description,
		&i.Price,
		pq.Array(&i.Tags),
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, users_id, metadata, description, price, tags, location, created_at FROM products
WHERE created_at > NOW() - INTERVAL '30 days'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UsersID,
			&i.Metadata,
			&i.Description,
			&i.Price,
			pq.Array(&i.Tags),
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, users_id, metadata, description, price, tags, location, created_at FROM products
ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UsersID,
			&i.Metadata,
			&i.Description,
			&i.Price,
			pq.Array(&i.Tags),
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByTag = `-- name: ListProductsByTag :many
SELECT id, users_id, metadata, description, price, tags, location, created_at FROM products
WHERE tags @> ARRAY[$1]::text[]
ORDER BY created_at DESC
`

func (q *Queries) ListProductsByTag(ctx context.Context, dollar_1 []string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByTag, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UsersID,
			&i.Metadata,
			&i.Description,
			&i.Price,
			pq.Array(&i.Tags),
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByUser = `-- name: ListProductsByUser :many
SELECT id, users_id, metadata, description, price, tags, location, created_at FROM products
WHERE users_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProductsByUser(ctx context.Context, usersID int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByUser, usersID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UsersID,
			&i.Metadata,
			&i.Description,
			&i.Price,
			pq.Array(&i.Tags),
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByUserAndLocation = `-- name: ListProductsByUserAndLocation :many
SELECT id, users_id, metadata, description, price, tags, location, created_at FROM products
WHERE users_id = $1 AND location = $2
ORDER BY created_at DESC
`

type ListProductsByUserAndLocationParams struct {
	UsersID  int64
	Location string
}

func (q *Queries) ListProductsByUserAndLocation(ctx context.Context, arg ListProductsByUserAndLocationParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByUserAndLocation, arg.UsersID, arg.Location)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UsersID,
			&i.Metadata,
			&i.Description,
			&i.Price,
			pq.Array(&i.Tags),
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    metadata = $1,
    description = $2,
    price = $3,
    tags = $4,
    location = $5
WHERE id = $6
RETURNING id, users_id, metadata, description, price, tags, location, created_at
`

type UpdateProductParams struct {
	Metadata    json.RawMessage
	Description string
	Price       string
	Tags        []string
	Location    string
	ID          int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Metadata,
		arg.Description,
		arg.Price,
		pq.Array(arg.Tags),
		arg.Location,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UsersID,
		&i.Metadata,
		&i.Description,
		&i.Price,
		pq.Array(&i.Tags),
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}
